### ISSUE TITLE
Question regarding deployment

### ISSUE THREAD

**Issue by osukaa** [sandnap/contacts-ember-hapi#4]
When deploying this app to production what would actually serve the emberjs app with assets? Because I'm building an app in a similar fashion with the `/server` and `/client` folders. But I'm wondering what would be a best practice for this.

**Comment by sandnap** [comment]
I highly recommend checking out http://ember-cli.github.io/ember-cli-deploy/ for deploying the ember assets. This is my preferred option now however on projects I have worked on in the past I have used a variation of this technique with the non-html assets hosted on AWS S3 and the index.html file hosted on the API server (Rails or Node). With this technique I did some interesting stuff to ensure that the index.html file picked up the latest fingerprinted app.js & app.css files.
